language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r requirements-test.txt --use-mirrors"
before_script: "mv collab/local_settings_template.py collab/local_settings.py"
script: "python manage.py test"
